---
output: github_document
editor_options: 
  chunk_output_type: console
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Advent of code 2022
```{r warning = FALSE, message = FALSE}
library(tidyverse)
library(here)
```


## --- Day 1: Calorie Counting ---
### 1a
```{r}
d <- 
  readr::read_lines(here('2022', 'data-in', '1.txt')) |>
  as.numeric() |> 
  tibble(x = _) |> 
  mutate(g = case_when(is.na(x) ~ 1, TRUE ~ 0),
         g = cumsum(g)) |> 
  filter(!is.na(x))

d |> 
  group_by(g) |>
  summarise(calories = sum(x)) |>
  slice_max(calories, n=1)
```

### 1b
```{r}
d |> 
  group_by(g) |>
  summarise(calories = sum(x)) |>
  slice_max(calories, n=3) |> 
  summarise(sum(calories))
```


## --- Day 2: Rock Paper Scissors ---

### 2a
```{r}
result_lu <- c(l = 0, d = 3, w = 6)
shape_lu <- c(X = 1, Y = 2, Z = 3)

d <- 
  tibble(raw = read_lines(here('2022', 'data-in', '2.txt'))) |> 
  separate(raw, into = c('p1', 'p2'), sep = ' ', remove = FALSE) |> 
  mutate(p2_result = 
           case_when(
             p1 == 'A' & p2 == 'X' ~ 'd',
             p1 == 'A' & p2 == 'Y' ~ 'w',
             p1 == 'A' & p2 == 'Z' ~ 'l',
             p1 == 'B' & p2 == 'X' ~ 'l',
             p1 == 'B' & p2 == 'Y' ~ 'd',
             p1 == 'B' & p2 == 'Z' ~ 'w',
             p1 == 'C' & p2 == 'X' ~ 'w',
             p1 == 'C' & p2 == 'Y' ~ 'l',
             p1 == 'C' & p2 == 'Z' ~ 'd'),
         shape_point = shape_lu[p2],
         result_point = result_lu[p2_result],
         score = shape_point + result_point)

sum(d$score)

# Redefine result lookup
result_lu <- c(X = 0, Y = 3, Z = 6)

d <- 
  tibble(raw = read_lines(here('2022', 'data-in', '2.txt'))) |> 
  separate(raw, into = c('p1', 'p2_result'), sep = ' ', remove = FALSE) |> 
  mutate(p2 = 
           case_when(
             p1 == 'A' & p2_result == 'X' ~ 'Z',
             p1 == 'A' & p2_result == 'Y' ~ 'X',
             p1 == 'A' & p2_result == 'Z' ~ 'Y',
             p1 == 'B' & p2_result == 'X' ~ 'X',
             p1 == 'B' & p2_result == 'Y' ~ 'Y',
             p1 == 'B' & p2_result == 'Z' ~ 'Z',
             p1 == 'C' & p2_result == 'X' ~ 'Y',
             p1 == 'C' & p2_result == 'Y' ~ 'Z',
             p1 == 'C' & p2_result == 'Z' ~ 'X'),
         shape_point = shape_lu[p2],
         result_point = result_lu[p2_result],
         score = shape_point + result_point)

sum(d$score)
```

## --- Day 3: Rucksack Reorganization ---

### 3a
```{r}
priority_lu <- set_names(1:52, c(letters, LETTERS))

d <-
  read_lines(here('2022', 'data-in', '3.txt')) |> 
  tibble(raw = _) |> 
  mutate(nchar = nchar(raw),
         string = str_split(raw, ""),
         intersect = map2_chr(string, nchar, ~intersect(.x[1:(.y/2)], .x[((.y/2)+1):.y])),
         priority = priority_lu[intersect]) 

sum(d$priority)
```

### 3b
```{r}
d |> 
  mutate(g = rep(1:(nrow(d)/3), each = 3)) |> 
  group_by(g) |> 
  summarise(intersect = intersect(intersect(string[[1]], string[[2]]), string[[3]])) |> 
  mutate(priority = priority_lu[intersect]) |> 
  pull(priority) |> 
  sum()
```

## --- Day 4: Camp Cleanup ---

### 4a
```{r}
d <-
  read_lines(here('2022', 'data-in', '4.txt')) |> 
  tibble(raw = _) |> 
  separate(raw, into = c('e1', 'e2'), sep = ',') |> 
  separate(e1, into = c('e1_start', 'e1_end'), sep = '-', convert = TRUE) |> 
  separate(e2, into = c('e2_start', 'e2_end'), sep = '-', convert = TRUE) |> 
  mutate(
    e1 = map2(e1_start, e1_end, ~.x:.y),
    e2 = map2(e2_start, e2_end, ~.x:.y),
    intersect = map2(e1, e2, intersect)) |> 
  mutate(full_cover = lengths(intersect) == lengths(e1) | lengths(intersect) == lengths(e2))

sum(d$full_cover)
```

### 4b
```{r}
d <- d |> mutate(any_cover = lengths(intersect) > 0)
sum(d$any_cover)  
```

## --- Day 5: Supply Stacks ---

Parse the starting (ground state) of the crates from the instructions
```{r}
ground_state <- 
    read_fwf(here('2022', 'data-in', '5.txt'), n_max = 8) |> 
    map(~str_remove_all(.x, '[:PUNCT:]')) |> 
    map(~.x[!is.na(.x)])

# Make a copy of the ground state
ground_state_tmp <- ground_state
```

Parse the instructions to a dataframe
```{r}
ins <- 
    read_lines(here('2022', 'data-in', '5.txt'), skip = 10) |> 
    tibble(raw = _) |> 
    mutate(
        n = str_extract(raw, '(?<=move )[0-9]+') |> as.integer(),
        from = str_extract(raw, '(?<=from )[0-9]+') |> as.integer(),
        to = str_extract(raw, '(?<=to )[0-9]+') |> as.integer())
```

### 5a
```{r}
for(i in 1:nrow(ins)){
    # Select the 1:n crates from the FROM column and reverse their order
    # append them to the start of the TO column
    ground_state[[ins$to[i]]] <- 
        c(rev(ground_state[[ins$from[i]]][1:ins$n[i]]), ground_state[[ins$to[i]]])
    
    # Remove the 1:n crates from the FROM column
    ground_state[[ins$from[i]]] <- ground_state[[ins$from[i]]][-(1:ins$n[i])]}

# Extract and combine first crate of each column
ground_state |> map_chr(~.x[1]) |> paste0(collapse = "")
```

### 5b
```{r}
# Re initialise the ground state
ground_state <- ground_state_tmp

for(i in 1:nrow(ins)){
    # Select the 1:n crates from the FROM column and DO NOT reverse their order
    # append them to the start of the TO column
    ground_state[[ins$to[i]]] <- 
        c(ground_state[[ins$from[i]]][1:ins$n[i]], ground_state[[ins$to[i]]])
    
    ground_state[[ins$from[i]]] <- ground_state[[ins$from[i]]][-(1:ins$n[i])]}

# Extract and combine first crate of each column
ground_state |> map_chr(~.x[1]) |> paste0(collapse = "")
```

## --- Day 6: Tuning Trouble ---

```{r}
d <- (read_lines(here('2022', 'data-in', '6.txt')) |> str_split(""))[[1]]
```

### 6a
Start of package marker length = 4
```{r}
marker_length <- 4
for(i in marker_length:length(d)) if(n_distinct(d[(i-(marker_length-1)):i]) == marker_length) break
i
```

### 6b
Start of message marker length = 14
```{r}
marker_length <- 14
for(i in marker_length:length(d)) if(n_distinct(d[(i-(marker_length-1)):i]) == marker_length) break
i
```

